### PR TITLE
0.7 fixes part 4

### LINKED ISSUE #466: Issues found with 0.7.0
- [x] Fix text content styles
- [x] Fix links blending into the background color on works
- [x] Migration pages need to be reintegrated
- [x] Content filters should not be handled via cookies
- [x] Fix broken button styles on settings pages
- [x] Verify cover art uploading is working

### LINKED ISSUE #467: Users can't upload or change cover art
With the v0.7 update, users can't upload or change cover art

### LINKED ISSUE #478: User collections always displays edit and delete options
Any time a user, whether they are logged in or not, visits another user's collections page, they are able to see the "Edit" and "Delete" options.

While these buttons do not work, they should still be hidden to prevent confusion.

### LINKED ISSUE #485: Comment quotes are not styled
They should appear with the same styling you see in the comment box. 

image

### LINKED ISSUE #492: Pagination on /news is broken
When attempting to use the pagination buttons on ``/news`` the URL changes appropriately, however, the page is not updated unless a refresh is done. 

Example: https://i.gyazo.com/0a56df17e1638599c8ca984fd2cb8107.mp4

### PR DESCRIPTION
**Pull request by Figments**
- news cards now have a publish date
- content filters now require an age verification check
- description field has been removed as a requirement on the news form
- minor style adjustments on blog and news cards
- news feed should now take the page query into account (closes #492 )
- collection cards no longer display controls to anyone but the owner (closes #478 )
- cover art uploading fixed (closes #466, closes #467 )
- avatar uploading fixed (hopefully)
- comment quotes are now styled (closes #485 )

### CODE REVIEW

File: libs/client/my-stuff/src/lib/components/upload-cover-art/upload-cover-art.component.ts [hunk 1]
```diff
@@ -128,16 +135,16 @@ export class UploadCoverArtComponent {
...
         this.uploader.clearQueue();
         this.uploader.addToQueue([this.fileToReturn]);
 
-        this.stuff.uploadCoverArt(this.uploader);
-        this.loading = false;
-        this.dialogRef.close();
+        await this.stuff.uploadCoverArt(this.uploader).then(() => {
+            this.loading = false;
+            this.dialogRef.close();
+        });
```
Comment (pingzing) [inline libs/client/my-stuff/src/lib/components/upload-cover-art/upload-cover-art.component.ts:147]: Figs what have I told you about .`then()`

_you are even using `await` what are you doing_

Comment (Figments) [reply libs/client/my-stuff/src/lib/components/upload-cover-art/upload-cover-art.component.ts:147]: oh that's so the dialog doesn't close until the upload is successful; without that it closes too early

Comment (pingzing) [reply libs/client/my-stuff/src/lib/components/upload-cover-art/upload-cover-art.component.ts:147]: actually, the more I read this, the less sense it makes. please hold while I pull this locally

**Review by pingzing — APPROVED** [review]
